#!/bin/bash

APPNAME="$1"
BUILDCONFIGS=(
  "darwin amd64"
  "darwin arm64"
  "linux amd64"
  "linux arm"
  "linux arm64"
  "windows amd64"
)
buildflags="$2"
tag="$3"

for bc in "${BUILDCONFIGS[@]}"; do
  os=${bc% *}
  arch=${bc#* }
  ext=""
  if [[ "${os}" = "windows" ]]; then
    ext=".exe"
  fi
  GOOS="${os}" GOARCH="${arch}" go build -o "${buildflags}" "${APPNAME}-${tag}-${os}-${arch}${ext}"
done