#!/bin/bash

APPNAME="go-discord-archiver"
BUILDCONFIGS=(
  "darwin amd64"
  "darwin arm64"
  "linux amd64"
  "linux arm"
  "linux arm64"
  "windows amd64"
)

for bc in "${BUILDCONFIGS[@]}"; do
  os=${bc% *}
  arch=${bc#* }
  ext=""
  if [[ "${os}" = "windows" ]]; then
    ext=".exe"
  fi
  GOOS="${os}" GOARCH="${arch}" go build -o "${APPNAME}-${os}-${arch}${ext}"
done